// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test, console2} from "forge-std/Test.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";

interface IPermit2 {
    function approve(address token, address spender, uint160 amount, uint48 expiration) external;
}

/// @notice Sends the EXACT UniversalRouter calldata the site produces, against the live
///         Doppler v4 CHIP/WETH pool on Base.
///
/// @dev The bytes are not written here. They are generated by the site's own encoder
///      (chipworks/lib/swap/v4.ts) into test/fork/v4calldata.json and read back, so what
///      this proves is what the site sends — not a Solidity re-implementation of it that
///      could agree with the test and disagree with production.
///
///      The Swap page could not swap at all before this: its only venue was a Uniswap v3
///      CHIP/USDC pool that was never created, so `chipUsdcVenue` returned {kind:'none'}
///      and every quote and execute short-circuited. The v4 pool holding all the real
///      depth was being read for the price ticker and had no execution path.
contract SiteSwapV4ForkTest is Test {
    address constant ROUTER = 0x6fF5693b99212Da76ad316178A184AB56D299b43;
    address constant PERMIT2 = 0x000000000022D473030F116dDEE9F6B43aC78BA3;
    address constant CHIP = 0x75Af968d2e58749FDA1b42C58186B76f5E511bA3;
    address constant WETH = 0x4200000000000000000000000000000000000006;
    address constant SAFE = 0xe1096B727499a3f70FaD8bc0267F5e69d01373C7;

    address trader = address(0xA11CE);

    string json;

    function setUp() public {
        json = vm.readFile("test/fork/v4calldata.json");
    }

    function _forked() internal view returns (bool) {
        return block.chainid == 8453;
    }

    /// BUY: native ETH in, $CHIP out, and NOTHING approved first.
    function test_buy_ethToChip_withNoApproval() public {
        if (!_forked()) { console2.log("skipped: not forked"); return; }

        bytes memory data = vm.parseJsonBytes(json, ".buy.calldata");
        uint256 value = vm.parseJsonUint(json, ".buy.valueWei");

        vm.deal(trader, 1 ether);
        uint256 chip0 = IERC20(CHIP).balanceOf(trader);
        uint256 eth0 = trader.balance;

        // No approve(), no Permit2, no WETH held. This is the whole point.
        assertEq(IERC20(WETH).balanceOf(trader), 0, "trader already holds WETH");
        assertEq(IERC20(CHIP).allowance(trader, ROUTER), 0, "trader pre-approved CHIP");

        vm.prank(trader);
        (bool ok, bytes memory ret) = ROUTER.call{value: value}(data);
        if (!ok) {
            console2.logBytes(ret);
            revert("buy reverted");
        }

        uint256 got = IERC20(CHIP).balanceOf(trader) - chip0;
        assertGt(got, 0, "no CHIP received");
        assertEq(eth0 - trader.balance, value, "spent something other than the stated value");
        assertEq(IERC20(WETH).balanceOf(trader), 0, "WETH was left stranded with the trader");
        assertEq(IERC20(WETH).balanceOf(ROUTER), 0, "WETH left in the router");

        console2.log("BUY  0.01 ETH ->", got / 1e18, "CHIP");
        console2.log("     implied CHIP per ETH:", (got / 1e18) * 100);
    }

    /// SELL: $CHIP in, native ETH out. Needs Permit2 - two approvals, then the swap.
    function test_sell_chipToEth_viaPermit2() public {
        if (!_forked()) return;

        bytes memory data = vm.parseJsonBytes(json, ".sell.calldata");
        uint256 amountIn = vm.parseJsonUint(json, ".sell.amountInWei");

        vm.deal(trader, 1 ether);
        vm.prank(SAFE);
        IERC20(CHIP).transfer(trader, amountIn);

        /*
          The two-step Permit2 dance the sell side needs:
            1. approve CHIP -> Permit2          a normal ERC-20 approval
            2. Permit2.approve(CHIP, router)    the router's allowance inside Permit2
          The site does both only when they are missing.
        */
        vm.prank(trader);
        IERC20(CHIP).approve(PERMIT2, type(uint256).max);
        vm.prank(trader);
        IPermit2(PERMIT2).approve(CHIP, ROUTER, uint160(amountIn), uint48(block.timestamp + 3600));

        uint256 eth0 = trader.balance;
        uint256 chip0 = IERC20(CHIP).balanceOf(trader);

        vm.prank(trader);
        (bool ok, bytes memory ret) = ROUTER.call(data);
        if (!ok) {
            console2.logBytes(ret);
            revert("sell reverted");
        }

        assertEq(chip0 - IERC20(CHIP).balanceOf(trader), amountIn, "wrong CHIP amount spent");
        assertGt(trader.balance, eth0, "no ETH received");
        // UNWRAP_WETH really unwrapped: the seller holds ETH, not WETH.
        assertEq(IERC20(WETH).balanceOf(trader), 0, "seller was left holding WETH");

        console2.log("SELL 1,000,000 CHIP -> wei:", trader.balance - eth0);
    }

    /// Without the Permit2 allowance the sell reverts. Proves step 2 is load-bearing.
    function test_sell_withoutPermit2_reverts() public {
        if (!_forked()) return;

        bytes memory data = vm.parseJsonBytes(json, ".sell.calldata");
        uint256 amountIn = vm.parseJsonUint(json, ".sell.amountInWei");

        vm.deal(trader, 1 ether);
        vm.prank(SAFE);
        IERC20(CHIP).transfer(trader, amountIn);

        // Only the plain ERC-20 approval. No Permit2.approve.
        vm.prank(trader);
        IERC20(CHIP).approve(PERMIT2, type(uint256).max);

        vm.prank(trader);
        (bool ok,) = ROUTER.call(data);
        assertFalse(ok, "sell succeeded without a Permit2 allowance");

        console2.log("confirmed: the sell needs Permit2.approve as well");
    }
}
